import os
import json
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
TOKEN_FILE = "youtube_token.json"

def _get_authenticated_service():
    creds = None
    token_json = os.environ.get("YOUTUBE_TOKEN_JSON")
    if token_json:
        creds = Credentials.from_authorized_user_info(json.loads(token_json, strict=False), SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            raise RuntimeError("YouTube auth required — run auth setup locally first")
    return build("youtube", "v3", credentials=creds)

def _make_title(raw: str) -> str:
    clean = raw.replace("\n", " ").replace("\r", "").strip()
    max_len = 90
    if len(clean) <= max_len:
        return clean + " #shorts"
    return clean[:max_len].rsplit(" ", 1)[0] + " #shorts"

def upload(video_path: str, post: dict) -> str:
    youtube = _get_authenticated_service()
    is_ai = post.get("post_id") == "ai_fallback"
    if is_ai:
        description = "Story generated by AI.\n\nSubscribe for more stories!"
        tags = ["shorts", "storytime", "aitoldme"]
    else:
        description = f"Story from r/{post['subreddit']}\n\n{post['permalink']}"
        tags = ["shorts", "reddit", "storytime", post["subreddit"]]
    body = {
        "snippet": {
            "title": _make_title(post["title"]),
            "description": description,
            "tags": tags,
        },
        "status": {"privacyStatus": "public"},
    }
    media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    response = request.execute()
    return f"https://youtu.be/{response['id']}"
